Fix type of monitor.filter.window: window is not an integer
cybozu-go/goma pull request #10
Opened 2018-11-19 07:10 UTC by arosh

This PR fixes the following bug.

```shell
$ goma register example.toml
Server error: 400 Bad Request
example: window is not an integer: 2 in filter
```

The content of `example.toml` is as follows.

```toml
[[monitor]]
name = "example"

  [monitor.probe]
  type = "exec"
  command = "true"

  [monitor.filter]
  type = "average"
  window = 2

  [[monitor.actions]]
  type = "exec"
  command = "true"
```

The TOML specification says that 64 bit range is expected.

See https://github.com/toml-lang/toml#integer

2018-11-19 08:03 UTC, ymmt2005 commented on cmd/goma/config_test.go
> +	defer os.Remove(tmpFileName)
err チェックの後にやりましょう。

2018-11-19 08:05 UTC, ymmt2005 commented on cmd/goma/config_test.go
> +	wtr := bufio.NewWriter(tmpFile)
bufio いらないでしょう。

```go
_, err = io.WriteString(tmpFile, content)
```

2018-11-19 08:07 UTC, ymmt2005 requested changes
指摘箇所の修正をお願いします。

2018-11-19 08:46 UTC, arosh commented
修正しました。確認お願いいたします。

2018-11-19 11:33 UTC, ymmt2005 commented
@arosh CI 動かしてほしいので、自分のレポジトリではなくこのレポジトリのブランチで作ってください。

2018-11-22 07:03 UTC, ymmt2005 commented
@arosh ping

2018-11-22 09:05 UTC, arosh commented
@ymmt2005 
@Hsn723 がCircleCIの設定を修正してくれたのでCIが実行されるようになりました。

2018-11-22 09:18 UTC, ymmt2005 approved these changes

2018-11-22 09:18 UTC, ymmt2005 commented
LGTM！

2018-11-22 09:18 UTC, merged